# Generated by Django 3.1 on 2020-10-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='cars'),
        ),
        migrations.AddField(
            model_name='book',
            name='zonar',
            field=models.CharField(default='', max_length=20),
        ),
    ]
