# Generated by Django 3.1 on 2020-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201009_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(default='', upload_to='static'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='static'),
        ),
    ]
